# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f90e7aae2c1704610dd53fb888eb3dadf288fef21c81bebf32c19c3102eb0a386228c6c76083df3c295087e013ccb756bd6adedf2af2009cd7b5fb2d5330b475

test:
  secret_key_base: 394f469e0035d873df391aefc9d831bbb39adfa6cf25360836e059ca182324d5695027e94a83cfe7de1fe7b245930bad494f86c0666fade3ac337397d29bfc5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
